# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every night at 4am)
  schedule: [{cron: "0 4 * * *"}]

  # Line below let you run workflow manually
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: AlienegraGeek
          template: classic

          config_display: large

#          plugin_languages: yes
#          plugin_languages_analysis_timeout: 30
#          plugin_languages_details: percentage, lines
#          plugin_languages_categories: markup, programming
#          plugin_languages_colors: github
#          plugin_languages_limit: 8
#          plugin_languages_recent_categories: data, markup, programming, prose
#          plugin_languages_recent_days: 60
#          plugin_languages_recent_load: 500
#          plugin_languages_sections: most-used
#          plugin_languages_other: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_lines: yes
